services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:80"            # Exposing Apache backend on port 8080
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
      - ml-api
    env_file:
      - .env
    networks:
      - internal

  ml-api:
    build:
      context: ./ml-api
      dockerfile: Dockerfile
    container_name: ml-api
    ports:
      - "5001:5000"           # Flask ML-API exposed on port 5001
    volumes:
      - ./ml-api:/app
    networks:
      - internal

  database:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/var/www/html
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
